name = input('Type your name:')
branch = input('Type your branch:')
gender = input('Type your gender:')
collegeName = input('Type your college name:')
age = int(input('Type your age:'))
print('Name:',name)
print('Branch:',branch)
print('Gender:',gender)
print('College name:',collegeName)
print('Age:',age)
